// gen_checknames.js — write checknames.h, the tables check.c takes from the reference: the
// checker's known library names (checker.js KNOWN_INTRINSIC_NAMES, in order — the order decides
// "did you mean" ties), the native subsystems (interpreter.js NATIVE_SUBSYSTEMS) and the infer
// strategies.
// usage: node tools/gen_checknames.js > checknames.h     (difftest.sh checks it is current)
const { KNOWN_INTRINSIC_NAMES, KNOWN_VERSIONS } = require('../../checker');
const { NATIVE_SUBSYSTEMS, SUPPORTED_INFER_STRATEGIES } = require('../../interpreter');
const q = (s) => JSON.stringify(s);
const list = (xs) => xs.length ? xs.map(q).join(', ') + ', NULL' : 'NULL';
const names = [...KNOWN_INTRINSIC_NAMES];
const lines = [
  '// checknames.h — generated by tools/gen_checknames.js from checker.js and interpreter.js;',
  '// do not edit.',
  '',
  '// The names the checker knows as library functions, in the reference\'s order.',
  'static const char *const CHECK_KNOWN_NAMES[] = {',
];
for (let i = 0; i < names.length; i += 8) lines.push('  ' + names.slice(i, i + 8).map(q).join(', ') + ',');
lines.push('};', `#define CHECK_KNOWN_NAMES_N ${names.length}`, '');
lines.push('// Entity base types the engine implements natively: sealed ones admit only their declared',
  '// actions and queries (NULL-terminated lists).');
lines.push('typedef struct { const char *name; bool sealed; const char *const *actions; const char *const *queries; } CheckSubsystem;');
const subs = Object.keys(NATIVE_SUBSYSTEMS);
for (const s of subs) {
  lines.push(`static const char *const SUB_${s}_actions[] = { ${list(NATIVE_SUBSYSTEMS[s].actions || [])} };`);
  lines.push(`static const char *const SUB_${s}_queries[] = { ${list(NATIVE_SUBSYSTEMS[s].queries || [])} };`);
}
lines.push('static const CheckSubsystem CHECK_SUBSYSTEMS[] = {');
for (const s of subs) lines.push(`  { ${q(s)}, ${NATIVE_SUBSYSTEMS[s].sealed ? 'true' : 'false'}, SUB_${s}_actions, SUB_${s}_queries },`);
lines.push('};', `#define CHECK_SUBSYSTEMS_N ${subs.length}`, '');
lines.push(`static const char *const CHECK_INFER_STRATEGIES[] = { ${list([...SUPPORTED_INFER_STRATEGIES])} };`);
lines.push('', '// Versions the `axiom X.Y` pragma may name.');
lines.push(`static const char *const CHECK_KNOWN_VERSIONS[] = { ${list([...KNOWN_VERSIONS])} };`);
process.stdout.write(lines.join('\n') + '\n');
