// checknames.h — generated by tools/gen_checknames.js from checker.js and interpreter.js;
// do not edit.

// The names the checker knows as library functions, in the reference's order.
static const char *const CHECK_KNOWN_NAMES[] = {
  "v2", "v3", "v3x", "v3y", "v3z", "v3xz", "v2dir", "q",
  "euler", "m4", "persp", "ortho", "lookat", "aabb", "clamp", "dist",
  "sphere", "box", "capsule", "abs", "floor", "ceil", "round", "sqrt",
  "sin", "cos", "tan", "asin", "acos", "atan", "log", "log10",
  "log2", "exp", "sign", "min", "max", "pow", "atan2", "random",
  "randomRange", "randomInt", "PI", "TAU", "E", "deg2rad", "rad2deg", "lerp",
  "map_range", "vision_cells", "cell_to_world", "linear", "in", "out", "inout", "bounce",
  "elastic", "bar", "json_parse", "json_stringify", "int", "float", "str", "type",
  "is_null", "is_number", "is_string", "is_array", "clock", "wrap", "fract", "smoothstep",
  "hypot", "trunc", "cbrt", "log1p", "band", "bor", "bxor", "bnot",
  "shl", "shr", "sum", "prod", "mean", "median", "mode", "variance",
  "stdev", "mod", "divmod", "gcd", "lcm", "fact", "comb", "perm",
  "is_prime", "primes", "isqrt", "inv_lerp", "round_to", "clamp01", "sinh", "cosh",
  "tanh", "ln", "is_nan", "is_int", "is_finite", "is_bool", "is_fn", "is_dict",
  "inf", "nan", "num", "to_fixed", "parse_int", "to_hex", "to_bin", "to_base",
  "big", "is_big", "seed", "random_range", "random_int", "pick", "shuffle", "gauss",
  "uuid", "sorted", "sort_by", "group_by", "count_by", "partition", "min_by", "max_by",
  "uniq", "zip", "unzip", "enumerate", "chunk", "windows", "flatten", "reversed",
  "take", "drop", "first", "last", "is_empty", "any", "all", "count",
  "find_index", "union", "intersect", "difference", "keys", "values", "items", "dict",
  "merge", "pick_keys", "omit_keys", "invert", "has_key", "clone", "deep_eq", "grid",
  "transpose", "ord", "chr", "lines", "words", "chars", "capitalize", "title",
  "reverse_str", "re_test", "re_match", "re_all", "re_sub", "re_split", "b64_encode", "b64_decode",
  "hash", "to_json", "from_json", "now", "time", "date_iso", "sleep", "read",
  "read_lines", "read_json", "write", "write_json", "append", "file_exists", "ls", "mkdir",
  "rm", "is_dir", "path_join", "input", "read_stdin", "args", "env", "eprint",
  "exit", "sh", "map", "filter", "reduce", "each", "find", "apply",
  "compose", "partial", "memo", "check", "check_eq", "sort", "print", "len",
  "range", "patrol_point", "observe", "nearest", "exists", "path", "raycast", "block_cell",
  "unblock_cell", "is_blocked",
};
#define CHECK_KNOWN_NAMES_N 234

// Entity base types the engine implements natively: sealed ones admit only their declared
// actions and queries (NULL-terminated lists).
typedef struct { const char *name; bool sealed; const char *const *actions; const char *const *queries; } CheckSubsystem;
static const char *const SUB_Fluid3D_actions[] = { "fluid_step", NULL };
static const char *const SUB_Fluid3D_queries[] = { NULL };
static const char *const SUB_NavMesh3D_actions[] = { NULL };
static const char *const SUB_NavMesh3D_queries[] = { "path", "raycast", "block_cell", "unblock_cell", "is_blocked", NULL };
static const char *const SUB_Body3D_actions[] = { "force", "impulse", "torque", NULL };
static const char *const SUB_Body3D_queries[] = { NULL };
static const char *const SUB_Camera_actions[] = { NULL };
static const char *const SUB_Camera_queries[] = { NULL };
static const char *const SUB_Light_actions[] = { NULL };
static const char *const SUB_Light_queries[] = { NULL };
static const char *const SUB_Environment_actions[] = { NULL };
static const char *const SUB_Environment_queries[] = { NULL };
static const char *const SUB_Audio3D_actions[] = { NULL };
static const char *const SUB_Audio3D_queries[] = { NULL };
static const char *const SUB_Listener_actions[] = { NULL };
static const char *const SUB_Listener_queries[] = { NULL };
static const char *const SUB_Net_actions[] = { "rpc", NULL };
static const char *const SUB_Net_queries[] = { NULL };
static const char *const SUB_Base_actions[] = { NULL };
static const char *const SUB_Base_queries[] = { NULL };
static const CheckSubsystem CHECK_SUBSYSTEMS[] = {
  { "Fluid3D", true, SUB_Fluid3D_actions, SUB_Fluid3D_queries },
  { "NavMesh3D", false, SUB_NavMesh3D_actions, SUB_NavMesh3D_queries },
  { "Body3D", false, SUB_Body3D_actions, SUB_Body3D_queries },
  { "Camera", false, SUB_Camera_actions, SUB_Camera_queries },
  { "Light", false, SUB_Light_actions, SUB_Light_queries },
  { "Environment", false, SUB_Environment_actions, SUB_Environment_queries },
  { "Audio3D", false, SUB_Audio3D_actions, SUB_Audio3D_queries },
  { "Listener", false, SUB_Listener_actions, SUB_Listener_queries },
  { "Net", false, SUB_Net_actions, SUB_Net_queries },
  { "Base", false, SUB_Base_actions, SUB_Base_queries },
};
#define CHECK_SUBSYSTEMS_N 10

static const char *const CHECK_INFER_STRATEGIES[] = { "particle", "exact", NULL };

// Versions the `axiom X.Y` pragma may name.
static const char *const CHECK_KNOWN_VERSIONS[] = { "0.1", "0.2", "0.3", "0.4", "0.5", "0.5.1", "0.6", "0.6.1", "0.7", "0.8", "0.8.1", "0.8.2", "0.8.3", "0.8.4", "0.8.5", "0.8.6", "0.8.7", "0.8.8", "0.8.9", "0.8.10", "0.8.11", "0.8.12", "0.8.13", "0.8.15", "0.8.16", "0.8.17", "0.9", "0.9.0", "0.9.1", "0.9.2", "0.9.3", NULL };
